import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import Header from "@/components/header";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`dark:bg-black dark:text-white`}>
        <main className="container mx-auto">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
